### ISSUE TITLE
Dynamic kick uses the wrong foot in a specific case

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_meta#304]
## Expected behavior
For the following goal, the kick chooses to use the left foot. However, it cannot reach the ball with the left foot.
```
goal: 
  header: 
    seq: 0
    stamp: 
      secs: 718
      nsecs: 808000000
    frame_id: "base_footprint"
  ball_position: 
    x: 0.1978674555508353
    y: -0.14818398242840478
    z: 0.0
  kick_direction: 
    x: 0.0
    y: 0.0
    z: -0.34289780745545134
    w: 0.9393727128473789
  kick_speed: 1.0
```

So maybe the kicking foot decision should be slightly adapted to work better in more cases.
